### ISSUE TITLE
[REQ] Medkit/medic module

### ISSUE THREAD

**Issue by pandathebeasty** [schwarper/cs2-store#2]
**What should do?**
Heal the player when type !medkit or !medic (add amount of health to current health)

**Config parameters**
1. amount of health
2. max use per round
3. credit cost

**Others**
1. medkits should be stackable 
2. medkits should decrease when are used

**What should be helpful**
1. command to buy an amount of items ( css_buy *item_name* *amount*[one if not specified] )

**Comment by paiuvlad** [comment]
@schwarper hello, any updates regarding this?

**Comment by schwarper** [comment]
This probably will be released as a new module but not soon because first i need to deal with important things
