### ISSUE TITLE
SQL queries Optimization

### ISSUE THREAD

**Issue by e54385991** [schwarper/cs2-store#25]
Should all SQL queries be asynchronous to minimize impact and prevent delays due to network issues?

**Comment by e54385991** [comment]
I made some attempts. I changed SavePlayerItem to SavePlayerItemAsync. Now, when purchasing items, there is no longer a noticeable lag due to long frame times.

**Comment by schwarper** [comment]
So far I haven't heard of anyone saying it fails because it's not asynchronous, so I don't think it would be a big problem.

**Comment by e54385991** [comment]
> So far I haven't heard of anyone saying it fails because it's not asynchronous, so I don't think it would be a big problem.

Mainly it causes server lag (blocking)

**Comment by schwarper** [comment]
> > So far I haven't heard of anyone saying it fails because it's not asynchronous, so I don't think it would be a big problem.
> 
> Mainly it causes server lag (blocking)
> 
> After switching to asynchronous, purchasing will not result in red high ping / lag ![111](https://private-user-images.githubusercontent.com/19951346/324944256-3080694b-8d73-49b6-8024-cca8574ffc06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDkxOTgsIm5iZiI6MTcxMzkwODg5OCwicGF0aCI6Ii8xOTk1MTM0Ni8zMjQ5NDQyNTYtMzA4MDY5NGItOGQ3My00OWI2LTgwMjQtY2NhODU3NGZmYzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDIxNDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNjAyNmEwODZlYTFhM2Y4NDU0Y2VmNmE5ODI1YmFlNWQ0YjU3ZDk5MTMwYWJmMzNlMmRkOTFlYmYzY2U5ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-APB2LsyyHIUIdQnOIZwpYHNjuM_6Z0sQeV3a_0szys) Database inserts usually take longer

Then, we can change it to async. It's okay
