### ISSUE TITLE
Issues related to sell 

### ISSUE THREAD

**Issue by e54385991** [schwarper/cs2-store#29]
I think we should use the prices in the database instead of the configuration file

**Comment by schwarper** [comment]
> I think we should use the prices in the database instead of the configuration file

In a similar manner to the real-world scenario, it is better to sell at the prevailing market price in my opinion.

**Comment by e54385991** [comment]
> > I think we should use the prices in the database instead of the configuration file
> 
> In a similar manner to the real-world scenario, it is better to sell at the prevailing market price in my opinion.

Perhaps we can provide a configuration option?

**Comment by e54385991** [comment]
#39

**Comment by schwarper** [comment]
Merged, thanks
