### ISSUE TITLE
On server restart

### ISSUE THREAD

**Issue by Wave55142** [schwarper/cs2-store#44]
When restarting server and when i connect to server the store player data does not load, it load only on reconnect, doesnt look good to let player reconnect everytime to load their store data.

**Comment by schwarper** [comment]
@e54385991 can you please check this?

**Comment by e54385991** [comment]
> @e54385991 can you please check this?

maybe temporarily unable to retrieve Steam ID or plugin has not yet initialized the connection to the database

**Comment by e54385991** [comment]
#46 need more tests

**Comment by schwarper** [comment]
> In my server, there are no issues with loading, and it operates normally. To enhance robustness, I have modified the code to include automatic retries. This can help in scenarios where the MySQL server experiences high latency.when player loading fails, it will be recorded in the error log.

When the server is restarted or at any time, when the player enters the server, it starts with -1 credit. It does not pull data from the database. There is still this problem

**Comment by e54385991** [comment]
> > In my server, there are no issues with loading, and it operates normally. To enhance robustness, I have modified the code to include automatic retries. This can help in scenarios where the MySQL server experiences high latency.when player loading fails, it will be recorded in the error log.
> 
> When the server is restarted or at any time, when the player enters the server, it starts with -1 credit. It does not pull data from the database. There is still this problem

it recover after the map changes?

**Comment by e54385991** [comment]
It should be resolved.
