### ISSUE TITLE
[REQ] Features

### ISSUE THREAD

**Issue by rodopoulos1** [schwarper/cs2-store#6]
- [ ] Add crash game https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/store_gamble_crash.sp

- [ ] Add Jackpot game (multiplayer game)  https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/store_gamble_jackpot.sp

- [ ] Add math quiz

- [ ] Add custom quiz by config

- [ ] Add Daily credits (7 days) If u enter today receive coins, tommorow more coins but have to enter everyday on the 7 days) https://hlmod.net/resources/shop-daily-credits.2547/

- [ ] Add Buy VIP from VIP CORE plugin by thesamefabious https://github.com/partiusfabaa/cs2-VIPCore/tree/v1.2.5

- [ ] Add buy Jumps, jumps in air like the vip core plugin by thesamefabious that have a module for that

- [ ] Add Open case with items System https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/store_misc_lootbox.sp

- [ ] Add Voucher System, so people and adm can generate a voucher for a person to receive coins

- [ ] Add Buy item an send it to a discord webhook (custom item)

- [ ] Add top list (TOP PLAYER COINS) (TOP 5 or 10)

**Comment by schwarper** [comment]
Several of your requests are individual plugins that should not be included in the store core.

**Comment by schwarper** [comment]
https://github.com/schwarper/cs2-store?tab=readme-ov-file#approved-modules
