### ISSUE TITLE
[BUG] SKIN EXPIRATION

### ISSUE THREAD

**Issue by Ez4LTarmy** [schwarper/cs2-store#62]
Skin that expired can still be equipped even it gone from inventory (did not switch back to default skin).
Player can have the skin almost permanently until they equip other model.

![image](https://github.com/schwarper/cs2-store/assets/97959351/86df2b2f-a17c-42ef-a629-2da0f00b8566)
This is when the skin exist in inventory.

![image](https://github.com/schwarper/cs2-store/assets/97959351/0bd7c1df-833e-4ee3-b60d-7a6025b875ca)
This is not but still equipping the skin.

**Comment by Sametyet53** [comment]
Do Player Models work on Every Map? dust2 mirage?

**Comment by Ez4LTarmy** [comment]
yes, player models work fine on every maps

**Comment by e54385991** [comment]
The data in the equipment information table still exists. It will be deleted when the server restarts

**Comment by Sametyet53** [comment]
> evet, oyuncu modelleri her haritada iyi çalışıyor

I am adding 2 workshop addresses, but only one works and the other does not accept it. How can I hide unused features?

**Comment by schwarper** [comment]
> The data in the equipment information table still exists. It will be deleted when the server restarts
