### ISSUE TITLE
[BUG] After server restart, every equipped item reseting and need to equip them again

### ISSUE THREAD

**Issue by originalaidn** [schwarper/cs2-store#71]
everything in the title, version 0.2.7
CSS version 246
META version 1293

**Comment by schwarper** [comment]
> same

For what items, it's fixed for playerskins, i tested it.

**Comment by originalaidn** [comment]
> > same
> 
> For what items? It's fixed for playerskins, i tested it.

yep, now playerskins works correctly (as i know, only that had the problem).
in my pov you can close it, dont know whats the problem for @rodopoulos1

**Comment by rodopoulos1** [comment]
Its playerskins on 0.2.7 but if its fixed on 0.2.8 ok np
