### ISSUE TITLE
[Issue] Custom models for M4A4 and M4A1-S

### ISSUE THREAD

**Issue by Letaryat** [schwarper/cs2-store#84]
Hi, so basically I am trying to do that players can buy two seperate custom models for M4A4 and M4A1-S. It works fine for M4A1-S but not for M4A4 untill I set "weapon" to m4a1 but then one model sets both for M4A4 and M4A1-S. 
This is my config with working 1s and not working for m4a4:

      "2": {
        "name": "M4A4",
        "uniqueid": "weapons/7ychu5/models/rif_m4a1/m4a1_chihiro/m4a4_chihiro.vmdl",
        "type": "customweapon",
        "weapon": "m4a4",
        "price": "0",
        "slot": "2",
        "enable": "true"
      },
      "3": {
        "name": "M4A1S",
        "uniqueid": "weapons/7ychu5/models/rif_m4a1s/m4a1_azusa/m4a1_azusa.vmdl",
        "type": "customweapon",
        "weapon": "m4a1",
        "price": "0",
        "slot": "3",
        "enable": "false"
      },

And it does not set M4A4 custom weapon model but for M4A1s it does.
On the other hand this config:

>
      "2": {
        "name": "M4A4",
        "uniqueid": "weapons/7ychu5/models/rif_m4a1/m4a1_chihiro/m4a4_chihiro.vmdl",
        "type": "customweapon",
        "weapon": "m4a1",
        "price": "0",
        "slot": "2",
        "enable": "true"
      },

With removed custom model for M4A1s sets both the same custom model for M4A4 and M4A1s. 
uniqueid as a model path works fine since I tried with famas and it worked. I think there is an issue that plugin thinks that M4A1 is both M4A4 and M4A1-S or maybe I did something wrong.

Anyway thanks for help.

**Comment by SkyJust4Fun** [comment]
weapon code name for guns in cs is:

m4a1 -> M4A4
m4a1_silencer -> M4a1-S

Try setting them like that :3

**Comment by Letaryat** [comment]
> weapon code name for guns in cs is:
> 
> m4a1 -> M4A4 m4a1_silencer -> M4a1-S
> 
> Try setting them like that :3
> 
> That's all i know, i didn't even worked with custom weapons yet. So it might work or not just try it :3


Thanks for respond but unfortunately it still bugs :(

**Comment by schwarper** [comment]
M4A4 -> `m4a1`

M4A1 -> `m4a1_silencer`

Can you try this?

**Comment by Letaryat** [comment]
> M4A4 -> `m4a1`
> 
> M4A1 -> `m4a1_silencer`
> 
> Can you try this?

Nothing changes unfortunately. I noticed that Ticho have the same issue on CSS Discord: https://discord.com/channels/1160907911501991946/1160907912445710480/1271580552251834368

**Comment by schwarper** [comment]
https://github.com/schwarper/cs2-store/commit/95aa78875bda284721ae0cdd405bbd051a3aaafe
