### ISSUE TITLE
commands when WSDA

### ISSUE THREAD

**Issue by M4nn3s** [schwarper/cs2-store#92]
Hi, when it is chat based, you can use css_1, css_2, ect. to navigate in the menu to easy make binds, and easyer to use.

If WSDA is enabled, is there then any commands to use for the same purpose? 

Best regards

**Comment by M4nn3s** [comment]
And also, is there a command to equip a item? (Like /equip pepe)

**Comment by schwarper** [comment]
> Hi, when it is chat based, you can use css_1, css_2, ect. to navigate in the menu to easy make binds, and easyer to use.
> 
> If WSDA is enabled, is there then any commands to use for the same purpose?
> 
> Best regards

Unfortunately...
