### ISSUE TITLE
KitsuneMenu

### ISSUE THREAD

**Issue by gha241** [schwarper/cs2-store#95]
Will you add KitsuneMenu to the plugin?

**Comment by gha241** [comment]
@schwarper

**Comment by schwarper** [comment]
> Will you add KitsuneMenu to the plugin?

KitsuneMenu?

**Comment by gha241** [comment]
that's what I mean
![IMG_20241013_081906](https://github.com/user-attachments/assets/627ff319-ab94-4fd5-844b-a6fc6ffb7b88)

**Comment by schwarper** [comment]
> that's what I mean 

It's almost same as WASD menu, so i probably won't change it.
If you want this menu, you can do it and pr maybe
