### ISSUE TITLE
[Need Help] About the playermodel skins

### ISSUE THREAD

**Issue by DearCrazyLeaf** [schwarper/cs2-store#97]
How do I use this new function which is added in 1.4v? I read the example and cant understand its usage.
example:
> "1": {
        "name": "Fernandez Frogman",
        "uniqueid": "characters/models/ctm_diver/ctm_diver_variantb.vmdl",
        "armModel": "",
        "type": "playerskin",
        "price": "0",
        "slot": "1",
        "disable_leg": "false",
        "expiration": "0",
        "hide": "false",
        "enable": "true"
      },

So if I have a model and its has 2 or 3 skins(one model itself, 2 or 3 clothes can be changed), how can I change it?

And I have another question, can you add a command that can disable or enable player's lower body? like "!legs".

**Comment by schwarper** [comment]
@DearCrazyLeaf 
I couldn't really understand what you were asking. Could you expand on the question?

**Comment by DearCrazyLeaf** [comment]
@schwarper 
So I have got a model which has multiple replaceable skins, 
![a58b7b37-9cf8-476b-8994-586f10ed253a](https://github.com/user-attachments/assets/93330410-ab92-45de-8f92-125ab8a8d80b)
As above
It means the model file has one model itself, and multiple clothes can be changed in this mesh group which is the function in Source2 Viewer.
The model vpk file:
![140164f4-4c3b-4cad-af7c-d91a7679b500](https://github.com/user-attachments/assets/8387a6d8-e30c-431e-8ff1-0b5eccbadf0b)
So I'm trying to figure out to how to implement the above function. But there is not a plugin can do this.

And I thought you updated this feature in 1.4 update because its log shows "Added skin option for playerskins".

If I misunderstood, please ignore my issue.

**Comment by DearCrazyLeaf** [comment]
Oh "implement the above function" means Im trying to make it work on my server.

I'm sorry my english isnt well, so I can't express it very clearly.

**Comment by DearCrazyLeaf** [comment]
ok , thank you , ill try it.

and how can i use "flag" to apply items only for admins?
like:

> "flag": "#css/admin"

this?

**Comment by DearCrazyLeaf** [comment]
@schwarper I have one last question that is how to use "score tag","chat tag","chat color"and"name color"?

I added it to my server, and it was showed in store, but I cant choose to use it.

Using code which is in the cs2-store-example.json:
> "scoretag": {
      "1": {
        "name": "Test",
        "uniqueid": "scoretag_test",
        "type": "scoretag",
        "price": "0",
        "slot": "1",
        "scoretag": "Test"
      }
    },
    "chattag": {
      "1": {
        "name": "Test",
        "uniqueid": "chattag_test",
        "type": "chattag",
        "price": "0",
        "slot": "1",
        "chattag": "Test"
      }
    },
    "chatcolor": {
      "1": {
        "name": "Red",
        "uniqueid": "chatcolor_red",
        "type": "chatcolor",
        "price": "0",
        "slot": "1",
        "chatcolor": "{red}"
      }
    },
    "namecolor": {
      "1": {
        "name": "Red",
        "uniqueid": "namecolor_red",
        "type": "namecolor",
        "price": "0",
        "slot": "1",
        "chatcolor": "{red}"
      }
    }

Dosen't it done yet? If it is please ignore.

**Comment by schwarper** [comment]
> @schwarper I have one last question that is how to use "score tag","chat tag","chat color"and"name color"?
> 
> I added it to my server, and it was showed in store, but I cant choose to use it.
> Dosen't it done yet? If it is please ignore.

It's deleted but it will be released asap
